(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> Set: no tables selected"
p3
sS'layer'
p4
S'/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x10b47deb0, file "/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py:ecu_list", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/restricted.py", line 216, in restricted\n    exec(ccode, environment)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py:ecu_list", line 245, in <module>\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/globals.py", line 405, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py:ecu_list", line 229, in ecu_list\n  File "/usr/local/lib/python2.7/site-packages/pydal/objects.py", line 2045, in select\n    return adapter.select(self.query, fields, attributes)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/sqlite.py", line 82, in select\n    return super(SQLite, self).select(query, fields, attributes)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 741, in select\n    colnames, sql = self._select_wcols(query, fields, **attributes)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 605, in _select_wcols\n    raise SyntaxError(\'Set: no tables selected\')\nSyntaxError: Set: no tables selected\n'
p11
s.